#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'USAGE'
Usage: WINGS_INSTALL_CONFIRM=YES sudo ./install.sh --wings

Installs Docker, downloads Wings for amd64 or arm64, creates a systemd unit,
and leaves /etc/pterodactyl/config.yml for configuration generated by the
Pterodactyl Panel.
USAGE
  exit 0
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo "Error: run this installer as root or with sudo." >&2
  exit 1
fi

if [[ "${WINGS_INSTALL_CONFIRM:-}" != "YES" ]]; then
  cat >&2 <<'NOTICE'
This will install Docker and the official Pterodactyl Wings binary on this
Linux host. It requires a supported Linux VPS with systemd and may change
Docker and service configuration. It does not create a Panel node or generate
Wings config.yml automatically.

Set WINGS_INSTALL_CONFIRM=YES to continue, or run with --help.
NOTICE
  exit 2
fi

if [[ "${1:-}" != "" ]]; then
  echo "Error: unknown option: ${1}" >&2
  exit 2
fi

if ! command -v apt-get >/dev/null 2>&1; then
  echo "Error: this installer currently supports Debian/Ubuntu hosts with apt-get." >&2
  exit 1
fi

apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl gnupg
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker

arch="$(dpkg --print-architecture)"
case "$arch" in
  amd64) wings_arch="amd64" ;;
  arm64) wings_arch="arm64" ;;
  *) echo "Error: unsupported Debian architecture: $arch" >&2; exit 1 ;;
esac

install -d -m 0755 /etc/pterodactyl
curl -fL -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_${wings_arch}"
chmod 0755 /usr/local/bin/wings

cat > /etc/systemd/system/wings.service <<'UNIT'
[Unit]
Description=Pterodactyl Wings Daemon
After=docker.service
Requires=docker.service
PartOf=docker.service

[Service]
User=root
WorkingDirectory=/etc/pterodactyl
LimitNOFILE=4096
PIDFile=/var/run/wings/daemon.pid
ExecStart=/usr/local/bin/wings
Restart=on-failure
StartLimitInterval=180
StartLimitBurst=30
RestartSec=5s

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
if [[ ! -f /etc/pterodactyl/config.yml ]]; then
  cat <<'NEXT'
Wings is installed but not started because /etc/pterodactyl/config.yml is missing.
Create a node in the Pterodactyl Panel, copy its generated configuration into:
  /etc/pterodactyl/config.yml
Then validate and start Wings with:
  sudo wings --debug
  sudo systemctl enable --now wings
Official guide: https://pterodactyl.io/wings/1.0/installing.html
NEXT
else
  systemctl enable --now wings
  echo "Wings is installed and started. Check: systemctl status wings"
fi
